use_frameworks!

platform :ios, '8.0'

target 'SMQTestView_Example' do
  pod 'SMQTestView', :path => '../'

  target 'SMQTestView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
